export const countries = [
    { value: "Afghanistan", label: "Afghánistán" },
    { value: "Albania", label: "Albánie" },
    { value: "Algeria", label: "Alžírsko" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Antigua and Barbuda", label: "Antigua a Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Arménie" },
    { value: "Australia", label: "Austrálie" },
    { value: "Austria", label: "Rakousko" },
    { value: "Azerbaijan", label: "Ázerbájdžán" },
    { value: "Bahamas", label: "Bahamy" },
    { value: "Bahrain", label: "Bahrajn" },
    { value: "Bangladesh", label: "Bangladéš" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Bělorusko" },
    { value: "Belgium", label: "Belgie" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bhutan", label: "Bhútán" },
    { value: "Bolivia", label: "Bolívie" },
    { value: "Bosnia and Herzegovina", label: "Bosna a Hercegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazil", label: "Brazílie" },
    { value: "Brunei", label: "Brunej" },
    { value: "Bulgaria", label: "Bulharsko" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cabo Verde", label: "Kapverdy" },
    { value: "Cambodia", label: "Kambodža" },
    { value: "Cameroon", label: "Kamerun" },
    { value: "Canada", label: "Kanada" },
    { value: "Central African Republic", label: "Středoafrická republika" },
    { value: "Chad", label: "Čad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "Čína" },
    { value: "Colombia", label: "Kolumbie" },
    { value: "Comoros", label: "Komory" },
    { value: "Congo (Congo-Brazzaville)", label: "Kongo (Kongo-Brazzaville)" },
    { value: "Costa Rica", label: "Kostarika" },
    { value: "Croatia", label: "Chorvatsko" },
    { value: "Cuba", label: "Kuba" },
    { value: "Cyprus", label: "Kypr" },
    { value: "Czechia", label: "Česko" },
    { value: "Denmark", label: "Dánsko" },
    { value: "Djibouti", label: "Džibutsko" },
    { value: "Dominica", label: "Dominika" },
    { value: "Dominican Republic", label: "Dominikánská republika" },
    { value: "Ecuador", label: "Ekvádor" },
    { value: "Egypt", label: "Egypt" },
    { value: "El Salvador", label: "Salvador" },
    { value: "Equatorial Guinea", label: "Rovníková Guinea" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonsko" },
    { value: "Eswatini", label: "Eswatini" },
    { value: "Ethiopia", label: "Etiopie" },
    { value: "Fiji", label: "Fidži" },
    { value: "Finland", label: "Finsko" },
    { value: "France", label: "Francie" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambie" },
    { value: "Georgia", label: "Gruzie" },
    { value: "Germany", label: "Německo" },
    { value: "Ghana", label: "Ghana" },
    { value: "Greece", label: "Řecko" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hungary", label: "Maďarsko" },
    { value: "Iceland", label: "Island" },
    { value: "India", label: "Indie" },
    { value: "Indonesia", label: "Indonésie" },
    { value: "Iran", label: "Írán" },
    { value: "Iraq", label: "Irák" },
    { value: "Ireland", label: "Irsko" },
    { value: "Israel", label: "Izrael" },
    { value: "Italy", label: "Itálie" },
    { value: "Jamaica", label: "Jamajka" },
    { value: "Japan", label: "Japonsko" },
    { value: "Jordan", label: "Jordánsko" },
    { value: "Kazakhstan", label: "Kazachstán" },
    { value: "Kenya", label: "Keňa" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Korea, North", label: "Severní Korea" },
    { value: "Korea, South", label: "Jižní Korea" },
    { value: "Kosovo", label: "Kosovo" },
    { value: "Kuwait", label: "Kuvajt" },
    { value: "Kyrgyzstan", label: "Kyrgyzstán" },
    { value: "Laos", label: "Laos" },
    { value: "Latvia", label: "Lotyšsko" },
    { value: "Lebanon", label: "Libanon" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Libérie" },
    { value: "Libya", label: "Libye" },
    { value: "Liechtenstein", label: "Lichtenštejnsko" },
    { value: "Lithuania", label: "Litva" },
    { value: "Luxembourg", label: "Lucembursko" },
    { value: "Madagascar", label: "Madagaskar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malajsie" },
    { value: "Maldives", label: "Maledivy" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Marshall Islands", label: "Marshallovy ostrovy" },
    { value: "Mauritania", label: "Mauritánie" },
    { value: "Mauritius", label: "Mauricius" },
    { value: "Mexico", label: "Mexiko" },
    { value: "Micronesia", label: "Mikronésie" },
    { value: "Moldova", label: "Moldavsko" },
    { value: "Monaco", label: "Monako" },
    { value: "Mongolia", label: "Mongolsko" },
    { value: "Montenegro", label: "Černá Hora" },
    { value: "Morocco", label: "Maroko" },
    { value: "Mozambique", label: "Mosambik" },
    { value: "Myanmar (formerly Burma)", label: "Myanmar (dříve Barma)" },
    { value: "Namibia", label: "Namibie" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepál" },
    { value: "Netherlands", label: "Nizozemsko" },
    { value: "New Zealand", label: "Nový Zéland" },
    { value: "Nicaragua", label: "Nikaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigérie" },
    { value: "North Macedonia", label: "Severní Makedonie" },
    { value: "Norway", label: "Norsko" },
    { value: "Oman", label: "Omán" },
    { value: "Pakistan", label: "Pákistán" },
    { value: "Palau", label: "Palau" },
    { value: "Palestine State", label: "Stát Palestina" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua Nová Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Filipíny" },
    { value: "Poland", label: "Polsko" },
    { value: "Portugal", label: "Portugalsko" },
    { value: "Qatar", label: "Katar" },
    { value: "Romania", label: "Rumunsko" },
    { value: "Russia", label: "Rusko" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Saint Kitts and Nevis", label: "Svatý Kryštof a Nevis" },
    { value: "Saint Lucia", label: "Svatá Lucie" },
    { value: "Saint Vincent and the Grenadines", label: "Svatý Vincenc a Grenadiny" },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Sao Tome and Principe", label: "Svatý Tomáš a Princův ostrov" },
    { value: "Saudi Arabia", label: "Saúdská Arábie" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Srbsko" },
    { value: "Seychelles", label: "Seychely" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapur" },
    { value: "Slovakia", label: "Slovensko" },
    { value: "Slovenia", label: "Slovinsko" },
    { value: "Solomon Islands", label: "Šalamounovy ostrovy" },
    { value: "Somalia", label: "Somálsko" },
    { value: "South Africa", label: "Jižní Afrika" },
    { value: "South Sudan", label: "Jižní Súdán" },
    { value: "Spain", label: "Španělsko" },
    { value: "Sri Lanka", label: "Srí Lanka" },
    { value: "Sudan", label: "Súdán" },
    { value: "Suriname", label: "Surinam" },
    { value: "Sweden", label: "Švédsko" },
    { value: "Switzerland", label: "Švýcarsko" },
    { value: "Syria", label: "Sýrie" },
    { value: "Taiwan", label: "Tchaj-wan" },
    { value: "Tajikistan", label: "Tádžikistán" },
    { value: "Tanzania", label: "Tanzanie" },
    { value: "Thailand", label: "Thajsko" },
    { value: "Timor-Leste", label: "Východní Timor" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad and Tobago", label: "Trinidad a Tobago" },
    { value: "Tunisia", label: "Tunisko" },
    { value: "Turkey", label: "Turecko" },
    { value: "Turkmenistan", label: "Turkmenistán" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "Uganda", label: "Uganda" },
    { value: "Ukraine", label: "Ukrajina" },
    { value: "United Arab Emirates", label: "Spojené arabské emiráty" },
    { value: "United Kingdom", label: "Spojené království" },
    { value: "United States of America", label: "Spojené státy americké" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Uzbekistan", label: "Uzbekistán" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Vatican City", label: "Vatikán" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Yemen", label: "Jemen" },
    { value: "Zambia", label: "Zambie" },
    { value: "Zimbabwe", label: "Zimbabwe" },
];
