name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.1"

      - name: Install dependencies
        run: |
          cd weather
          npm install

      - name: Build project
        run: |
          CI=false npm run build
        working-directory: ./weather

      - name: Deploy to GitHub Pages
        run: |
          cd weather
          npm install -g gh-pages
          gh-pages -d build
