# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Github Pages

on:
  push:
    branches:
      - main

env:
  CI: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd weather
          npm install
          npm install -g gh-pages

      - name: Build applicatipon
        run: |
          ls -la
          cd weather
          npm run build

      - name: Configure Git
        run: |
          git config --global user.email jan.reisiegel@tul.com
          git config --global user.name JanReisiegel

      - name: Deploy Aplication to Github Pages
        run: |
          cd weather
          npm run deploy

#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#          cd weather
#          npm run deploy
