# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - weatherfrontend

on:
  push:
    branches:
      - main

env:
  CI: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd weather
          npm install
          npm install -g gh-pages

      - name: Build applicatipon
        run: |
          ls -la
          cd weather
          npm run build

      - name: Deploy Aplication to Github Pages
        run: |
          cd weather
          npm run deploy
